<?php

namespace App\Traits;

use App\Models\LectionNonce;

trait ValidateLectionNonce {

  /**
    * Determines if a nonce is valid. Makes additional checks to
    * ensure input is not fraudulent.
    * NOTE: nonce still exists after validation, must be deleted manually
    *
    * @param LectionNonce $nonce: the nonce generated by nonce
    * @param double $velocity: user's velocity (from result uploaded)
    *
    * @return boolean
    */
  public function validateLectionNonce($nonce, $velocity)
  {
    if($nonce) {  // nonce exists

        // calculate total time needed for lection
        $timeDiff = time() - $nonce->timestamp;

        // velocity of over 600 is not possible for humans (proof?)
        if($velocity > 600) return false;

        // convert keystrokes per min to key. per sec
        $velocity /= 60.0;

        // calculate approx characters typed by user
        $characters = $velocity * $timeDiff;

        // if the user could not type the amount of characters
        // in the calculated timeframe, user must be cheating
        // (minus a 5% margin of error that takes into account delays will submitting results)
        if($characters < $nonce->character_amount - ($nonce->character_amount * 0.05)) {

          return false;

        } else {

          return true;  // everything ok, results are valid and can be stored
        }
    }

    return false;
  }
}
